version: '3.8'
services:
  app:
    build: .
    container_name: php_app
    volumes:
      - .:/app
    ports:
      - "9000:9000"
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    ports:
      - "8080:80"
  phpunit:
    build: .
    container_name: phpunit_tester
    command: ["vendor/bin/phpunit", "tests"]
    volumes:
      - .:/app